FROM node:18

WORKDIR /app

# Salin hanya file dependency dulu
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Salin semua file project
COPY . .

# Jalankan dalam mode development
EXPOSE 3000
CMD ["npm", "run", "dev"]
